language: python
dist: xenial
python:
    - 3.6
    - 3.7
    - 3.8
install:
    - pip install tox-travis coveralls
script:
    - tox
after_success:
    - coveralls
cache:
  pip: true
notifications:
  webhooks:
    secure: "d0nSzvaIGJM5XYiJ65RWx0yY1NLTS3WjYrMBZ7m4glep3+NnzUSAu07B1cIUl9igz1+R4qU9Bus2hvyv2Dp8tt9hNuut59W0tVbD8XEdd42GzXTTJfHXyHxUkQQSYkzLA7fgViE1+X7FvJ/4KgqyLG/fks80zXi4r9MRTHEdUjUJAJYa7RCdwA15U/XVqEwcdA4/k9rIrP0+B70roRYl+lIwweihaABJmqMmX5VkCjXRWFAmKZqJ/PHU9iIaWB1IN18IkPxACdJr7boHzsWbrZVov476qzkyezTZyMO1Jhd/BTUejyZ4fpCD5xV+IQWITqDnCQrsVhH1oaWIWZ/SOs6n1eJriVGN71yJBZwrxCHF+xfV1JhUfGu9w/eJldXjgu7AMQR7cqK+0/X1AFcBfIEVG8cbGiCnY9tlTykOD7eDoOXiBK658eNarrDf+YFqfoOfs7p9ir32FEv00QvRMsi3fP/P5p9+fcVM/fR6ekFIGSyHHreKbUEK7KINVK7rUslIYl5/jTJ8fHpkJ7Ga11OqU2zAVY7S9obMNSLqCKMzluN8L5HpgDQjdLSgkqzIlQcV+u6lRqTW2V6Ted5RB29yHz85wTTNz/0xHZkDdEk2PqXDwsqr8oSYnTIJgCmIMfYnI3zaU6BIogK4unBu/ai7KwhZrBn9U14MDBllh3g="
