language: python
dist: xenial
python:
- 3.6
- 3.7
install:
- pip install tox-travis coveralls
script:
- tox
after_success:
- coveralls
cache:
  pip: true
notifications:
  webhooks:
    secure: mPTcEU2FiGToOD0Y8eqeOIoX6I0Gfh5k4VpMgSi+ygEz9EL9ZYSrUf8PdvuRD0eMnZ4HkP0oNBPpC/ruLCQfBW4kCzD++VuDdyvnNp2mF+q3a2D6FbXot2JfBPSr+bsmPLDUQgJvdvPbjtB9BRNX+DHbczQVo+MozAKpOdTMBpDa0jTFXrjc40D+2IzE8pwwmA2WIaGebLsHkGfe8sgJipLWzZwUQouZWQUyWJ9+7CXJE74hpixteqZntYiwfko0q/KpcyAuvNHZGBJtQOogHdDOvO0ifrR8vqcOSfmZI0uUe8p2HfwqZOf55itRCZP6ZYeT2psS8cDh5bf5hF7EKRMOnC34NdbzmbsuLe1MrsuTrSDMcYwj32i9f7VyhrwKYpniUpahRvFQN+1EFNx6TIW2ClccPsf8Q/00k2LvjtVMmZnwxcnYVeHCwr1mIfLUGuyavd06MiXX6RBf6oWKsEAvmS9f7QfEKG9gNX5oKWyxRY/i1gYq6vjbMtcms56Qmw+kWdxK9rA0fQ2K3YVDEM76VYbgPkh4OiUuMdMi0wPf3TIL+CaAoQ8pZYLB21F731khMhtxlGrFXSfc4O6F/OPzhsXJ0c7EnCZTPJWawdbA5dQXvnOUY8V5NWu9OLXWFFa7E5V2MmQp+CvDDJ8oI0uMCC/SjTMnRwkPpbTyHdE=
